### ISSUE TITLE
Built error with gcc 5

### ISSUE THREAD

**Issue by JoergFF** [algernon/libmongo-client#36] opened 2015-06-20 15:19 UTC
Hi,

at built with gcc 5 this test fails:

[quote]
#   Failed test 'bson_cursor_find() should wrap over if neccessary'
#   at ../../tests/unit/bson/bson_cursor_find.c line 24.
unit/bson/bson_cursor_find .............................................. 
Failed 1/7 subtests 
[/quote]

CU
Jörg

**Comment by algernon** [comment] 2015-06-22 10:16
I can't reproduce this problem (Debian Jessie + gcc-5 from unstable). Can you provide a full build log?

Also, which version did you test with gcc5? Does it still fail if compiled with gcc4.9 or clang?

**Comment by algernon** [comment] 2015-06-22 10:50
Turns out I needed to use -O3, because the bug was in a place that was only buggy with certain optimisations applied. Issue fixed on master.

**Closed** 2015-06-22 10:49 UTC
